default:
  parent: "syn20400157"
  path_to_markdown: !expr system.file("using-the-dccvalidator-app-amp-ad.Rmd", package = "dccvalidator")
  study_table: "syn11363298"
  samples_table: "syn21578908"
  annotations_table: "syn10242922"
  annotations_link: "https://shinypro.synapse.org/users/nsanati/annotationUI/"
  templates_link: "https://www.synapse.org/#!Synapse:syn18512044"
  study_link_animal: "https://adknowledgeportal.synapse.org/#/Explore/Studies?Study=syn8391648"
  study_link_human: "https://adknowledgeportal.synapse.org/#/Explore/Studies?Study=syn3159438"
  study_link_ref: ""
  teams:
    - "273957"
  templates:
    manifest_template: "syn20820080"
    individual_templates:
      human: "syn12973254"
      mouse or other animal model: "syn12973253"
    biospecimen_templates:
      mouse or other animal model: "syn12973252"
      human: "syn12973252"
      drosophila: "syn20673251"
    assay_templates:
      rnaSeq: "syn12973256"
      proteomics: "syn12973255"
  species_list:
    - "mouse or other animal model"
    - "human"
    - "drosophila"
  complete_columns:
    manifest:
      - "parent"
      - "path"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"
  contact_email: "karawoo@synapse.org"
